name: Orders Api Deployment

on:
  push:
    branches:
      - '**'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm ci
      - run: npx nx workspace-lint --base=origin/master
      - run: npx nx format:check --base=origin/master
      - run: npx nx affected --target=lint --parallel=3 --base=origin/master
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage --base=origin/master
      - run: npx nx affected --target=build --parallel=3 --base=origin/master
